### ISSUE TITLE
Proper World Login Settings

### ISSUE THREAD

**Issue by OhRetro** [Iru21/Authy#65]
as the title says, a proper setting that uses a world to be the login/registration 

example:
```yml
loginWorld:
  world: login_void
  destinationWorld: world # or just teleport the player back to known last position
```
