### ISSUE TITLE
Configuration options explanation

### ISSUE THREAD

**Issue by OortCloud42** [Iru21/Authy#68]
Adding more explanations to the config file or to the wiki would be a huge help. It might not be obvious for first-time users what they do or what units they use.
Examples:
```yaml
nameValidation: true

timeout: 60

sessionExpiresIn: 48

effects:
  title: true
  particles: true
  sounds: true
  blindness: false
```
