### ISSUE TITLE
Only the admin can register.

### ISSUE THREAD

**Issue by Mcvell** [Iru21/Authy#69]
And why can only the admin use the "Login" and "Registration" commands? How can I change it?

**Comment by Limeen** [comment]
You have to give the permission authy.register to your players

**Comment by Mcvell** [comment]
Hello, how do you do it?

**Comment by Limeen** [comment]
If you don't use any permission plugin copy that in your "permissions.yml" file a the root of your server:

```
server.basics:
       description: Basic permissions for My Cool Server.
       default: true
       children:
          authy.login: true
          authy.register: true
          authy.remember: true
```
